<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5c9a1cc575c8f1f6a0b69073ba2054af
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5c9a1cc575c8f1f6a0b69073ba2054af::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5c9a1cc575c8f1f6a0b69073ba2054af::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5c9a1cc575c8f1f6a0b69073ba2054af::$classMap;

        }, null, ClassLoader::class);
    }
}
